<?php

use Core\ExceptionHandler;

$errorId = uniqid('error', true);
?>
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex">
    <title><?= escapeHtml($title) ?></title>
    <style>
        <?= preg_replace('#[\r\n\t ]+#', ' ', file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . 'debug.css')) ?>
    </style>

    <script>
        <?= file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . 'debug.js') ?>
    </script>
</head>

<body onload="init()">

    <!-- Header -->
    <div class="header">
        <div class="container">
            <h1><?= escapeHtml($title), escapeHtml($exception->getCode() ? ' #' . $exception->getCode() : '') ?></h1>
            <p>
                <?= nl2br(escapeHtml($exception->getMessage())) ?>
                <a href="https://www.google.com/search?q=<?= urlencode(preg_replace('#\'.*\'|".*"#Us', '', $exception->getMessage())) ?>"
                    rel="noreferrer" target="_blank">Look on web &rarr;</a>
            </p>
        </div>
    </div>

    <!-- Source -->
    <div class="container">
        <p><b><?= escapeHtml($file) ?></b> at line <b><?= escapeHtml($line) ?></b></p>

        <?php if (is_file($file)): ?>
            <div class="source">
                <?= ExceptionHandler::showFile($file, $line, 15); ?>
            </div>
        <?php endif; ?>
    </div>

    <div class="container">
        <?php
        $last = $exception;
        while ($prevException = $last->getPrevious()):
            $last = $prevException;
            $urlEncodedPrevExceptionMessage = urlencode(get_class($prevException) . ' ' . preg_replace('#\'.*\'|".*"#Us', '', $prevException->getMessage()));
            $prevExceptionDetail = escapeHtml(get_class($prevException)) . ' | ' . escapeHtml($prevException->getCode() ? ' #' . $prevException->getCode() : '');
            ?>
            <p>
                Caused by: <?= $prevExceptionDetail ?>
                <?= nl2br(escapeHtml($prevException->getMessage())) ?>
                <a href="https://www.google.com/search?q=<?= $urlEncodedPrevExceptionMessage ?>" rel="noreferrer"
                    target="_blank">
                    search &rarr;
                </a>
                <?= escapeHtml($prevException->getFile()) . ':' . $prevException->getLine() ?>
            </p>
        <?php endwhile; ?>
    </div>



    <?php if (true || (defined('SHOW_DEBUG_BACKTRACE') && SHOW_DEBUG_BACKTRACE)): ?>
        <div class="container">

            <ul class="tabs" id="tabs">
                <li><a href="#backtrace">Backtrace</a></li>
                <li><a href="#server">Server</a></li>
                <li><a href="#request">Request</a></li>
                <li><a href="#response">Response</a></li>
                <li><a href="#files">Files</a></li>
                <li><a href="#memory">Memory</a></li>
            </ul>

            <div class="tab-content">

                <!-- Backtrace -->
                <div class="content" id="backtrace">

                    <ol class="trace">
                        <?php foreach ($trace as $index => $row): ?>

                            <li>
                                <p>
                                    <!-- Trace info -->
                                    <?php if (isset($row['file']) && is_file($row['file'])): ?>
                                        <?php
                                        if (isset($row['function']) && in_array($row['function'], ['include', 'include_once', 'require', 'require_once'], true)) {
                                            echo escapeHtml($row['function'] . ' ' . $row['file']);
                                        } else {
                                            echo escapeHtml($row['file'] . ' : ' . $row['line']);
                                        }
                                        ?>
                                    <?php else: ?>
                                        {PHP internal code}
                                    <?php endif; ?>

                                    <!-- Class/Method -->
                                    <?php if (isset($row['class'])): ?>
                                        &nbsp;&nbsp;&mdash;&nbsp;&nbsp;<?= escapeHtml($row['class'] . $row['type'] . $row['function']) ?>
                                        <?php if (!empty($row['args'])): ?>
                                            <?php $argsId = $errorId . 'args' . $index ?>
                                            ( <a href="#" onclick="return toggle('<?= escapeHtml($argsId) ?>');">arguments</a> )
                                        <div class="args" id="<?= escapeHtml($argsId) ?>">
                                            <table cellspacing="0">

                                                <?php
                                                $params = null;
                                                // Reflection by name is not available for closure function
                                                if (substr($row['function'], -1) !== '}') {
                                                    $mirror = isset($row['class']) ? new ReflectionMethod($row['class'], $row['function']) : new ReflectionFunction($row['function']);
                                                    $params = $mirror->getParameters();
                                                }

                                                foreach ($row['args'] as $key => $value): ?>
                                                    <tr>
                                                        <td><code><?= escapeHtml(isset($params[$key]) ? '$' . $params[$key]->name : "#{$key}") ?></code>
                                                        </td>
                                                        <td>
                                                            <pre><?= escapeHtml(print_r($value, true)) ?></pre>
                                                        </td>
                                                    </tr>
                                                <?php endforeach ?>

                                            </table>
                                        </div>
                                    <?php else: ?>
                                        ()
                                    <?php endif; ?>
                                <?php endif; ?>

                                <?php if (!isset($row['class']) && isset($row['function'])): ?>
                                    &nbsp;&nbsp;&mdash;&nbsp;&nbsp; <?= escapeHtml($row['function']) ?>()
                                <?php endif; ?>
                                </p>

                                <!-- Source? -->
                                <?php if (isset($row['file']) && is_file($row['file']) && isset($row['class'])): ?>
                                    <div class="source">
                                        <?= ExceptionHandler::showFile($row['file'], $row['line']) ?>
                                    </div>
                                <?php endif; ?>
                            </li>

                        <?php endforeach; ?>
                    </ol>

                </div>

                <!-- Server -->
                <div class="content" id="server">
                    <?php foreach (['_SERVER', '_SESSION'] as $var): ?>
                        <?php
                        if (empty($GLOBALS[$var]) || !is_array($GLOBALS[$var])) {
                            continue;
                        } ?>

                        <h3>$<?= escapeHtml($var) ?></h3>

                        <table>
                            <thead>
                                <tr>
                                    <th>Key</th>
                                    <th>Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($GLOBALS[$var] as $key => $value): ?>
                                    <tr>
                                        <td><?= escapeHtml($key) ?></td>
                                        <td>
                                            <?php if (is_string($value)): ?>
                                                <?= escapeHtml($value) ?>
                                            <?php else: ?>
                                                <pre><?= escapeHtml(print_r($value, true)) ?></pre>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>

                    <?php endforeach ?>

                    <!-- Constants -->
                    <?php $constants = get_defined_constants(true); ?>
                    <?php if (!empty($constants['user'])): ?>
                        <h3>Constants</h3>

                        <table>
                            <thead>
                                <tr>
                                    <th>Key</th>
                                    <th>Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($constants['user'] as $key => $value): ?>
                                    <tr>
                                        <td><?= escapeHtml($key) ?></td>
                                        <td>
                                            <?php if (is_string($value)): ?>
                                                <?= escapeHtml($value) ?>
                                            <?php else: ?>
                                                <pre><?= escapeHtml(print_r($value, true)) ?></pre>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php endif; ?>
                </div>

                <!-- Request -->
                <div class="content" id="request">
                    <?php $request = request() ?>

                    <table>
                        <tbody>
                            <tr>
                                <td style="width: 10em">Path</td>
                                <td><?= escapeHtml($request->getUri()) ?></td>
                            </tr>
                            <tr>
                                <td>HTTP Method</td>
                                <td><?= escapeHtml(strtoupper($request->method())) ?></td>
                            </tr>
                            <tr>
                                <td>IP Address</td>
                                <td><?= escapeHtml('0.0.0.0') ?></td>
                            </tr>
                            <tr>
                                <td style="width: 10em">Is AJAX Request?</td>
                                <td><?= 'NIL' ?></td>
                            </tr>
                            <tr>
                                <td>Is CLI Request?</td>
                                <td><?= $request->isCli() ? 'Yes' : 'No' ?></td>
                            </tr>
                            <tr>
                                <td>Is Secure Request?</td>
                                <td><?= 'NIL' ?></td>
                            </tr>
                            <tr>
                                <td>User Agent</td>
                                <td><?= escapeHtml('NIL') ?></td>
                            </tr>

                        </tbody>
                    </table>


                    <?php $empty = true; ?>
                    <?php foreach (['_GET', '_POST', '_COOKIE'] as $var): ?>
                        <?php
                        if (empty($GLOBALS[$var]) || !is_array($GLOBALS[$var])) {
                            continue;
                        } ?>

                        <?php $empty = false; ?>

                        <h3>$<?= escapeHtml($var) ?></h3>

                        <table style="width: 100%">
                            <thead>
                                <tr>
                                    <th>Key</th>
                                    <th>Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($GLOBALS[$var] as $key => $value): ?>
                                    <tr>
                                        <td><?= escapeHtml($key) ?></td>
                                        <td>
                                            <?php if (is_string($value)): ?>
                                                <?= escapeHtml($value) ?>
                                            <?php else: ?>
                                                <pre><?= escapeHtml(print_r($value, true)) ?></pre>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>

                    <?php endforeach ?>

                    <?php if ($empty): ?>

                        <div class="alert">
                            No $_GET, $_POST, or $_COOKIE Information to show.
                        </div>

                    <?php endif; ?>

                    <?php $headers = []; ?>
                    <?php if (!empty($headers)): ?>

                        <h3>Headers</h3>

                        <table>
                            <thead>
                                <tr>
                                    <th>Header</th>
                                    <th>Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($headers as $header): ?>
                                    <tr>
                                        <td><?= escapeHtml($header->getName()) ?></td>
                                        <td><?= escapeHtml($header->getValueLine()) ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>

                    <?php endif; ?>
                </div>

                <!-- Response -->
                <?php
                $response = response();
                $response->setStatusCode(http_response_code());
                ?>
                <div class="content" id="response">
                    <table>
                        <tr>
                            <td style="width: 15em">Response Status</td>
                            <td><?= escapeHtml('NIL') ?></td>
                        </tr>
                    </table>

                    <?php $headers = []; ?>
                    <?php if (!empty($headers)): ?>
                        <?php natsort($headers) ?>

                        <h3>Headers</h3>

                        <table>
                            <thead>
                                <tr>
                                    <th>Header</th>
                                    <th>Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach (array_keys($headers) as $name): ?>
                                    <tr>
                                        <td><?= escapeHtml($name) ?></td>
                                        <td><?= escapeHtml('NIL') ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>

                    <?php endif; ?>
                </div>

                <!-- Files -->
                <div class="content" id="files">
                    <?php $files = get_included_files(); ?>

                    <ol>
                        <?php foreach ($files as $file): ?>
                            <li><?= escapeHtml($file) ?></li>
                        <?php endforeach ?>
                    </ol>
                </div>

                <!-- Memory -->
                <div class="content" id="memory">

                    <table>
                        <tbody>
                            <tr>
                                <td>Memory Usage</td>
                                <td><?= escapeHtml('NIL') ?></td>
                            </tr>
                            <tr>
                                <td style="width: 12em">Peak Memory Usage:</td>
                                <td><?= escapeHtml('NIL') ?></td>
                            </tr>
                            <tr>
                                <td>Memory Limit:</td>
                                <td><?= escapeHtml(ini_get('memory_limit')) ?></td>
                            </tr>
                        </tbody>
                    </table>

                </div>

            </div> <!-- /tab-content -->

        </div> <!-- /container -->
    <?php endif; ?>

    <div class="footer">
        <div class="container">

            <p>
                Displayed at <?= escapeHtml(date('H:i:sa')) ?> &mdash;
                PHP: <?= escapeHtml(PHP_VERSION) ?> &mdash;
                CosmicPHP: <?= escapeHtml('1.0') ?> --
                Environment: <?= env('ENVIRONMENT') ?>
            </p>
        </div>
    </div>

</body>

</html>